import "./globals.css";
import { ThemeModeScript } from "flowbite-react";
import Provider from "@/utils/Provider/Provider";
import Navbar from "@/components/Shared/Navbar/Navbar";
import Footer from "@/components/Shared/Footer/Footer";
import { inter } from "./fonts";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>

        <header>
          <Navbar />
        </header>

        <Provider>
          {children}
        </Provider>


        <Footer />
      </body>
    </html>
  );
}
